import { Tag } from "react-tag-input";

export const suggestions: Tag[] = [
  { id: "1.", text: "Python" },
  { id: "2.", text: "JavaScript/TypeScript" },
  { id: "3.", text: "Java" },
  //{id:"4.", text:"C/C++"},
  //{id:"5.", text:"Golang"},
  //{id:"6.", text:"Rust"},
  //{id:"7.", text:"Lua"},
  //{id:"8.", text:"PHP"},
  //{id:"9.", text:"C#"},
  //{id:"10.", text:"Ruby"},

  //{id:"11.", text:"React"},
  //{id:"12.", text:"Vue"},
  //{id:"13.", text:"Angular"},
  //{id:"14.", text:"Svelte"},
  //{id:"15.", text:"Gatsby"},
  //{id:"16.", text:"HTML/CSS"},

  //{id:"17.", text:"Flask"},
  //{id:"18.", text:"Express"},
  //{id:"19.", text:"Nest.js"},
  //{id:"20.", text:"Next.js"},
  //{id:"21.", text:"Nuxt.js"},
  //{id:"22.", text:"Spring Boot"},
  //{id:"23.", text:"Django"},
  //{id:"24.", text:"FastAPI"},
  //{id:"25.", text:"Laravel"},
  //{id:"26.", text:"Ruby on Rails"},
  //{id:"27.", text:"Node.js"},
  //{id:"28.", text:"GraphQL"},

  //{id:"29.", text:"Tailwind"},
  //{id:"30.", text:"Bootstrap"},
  //{id:"31.", text:"JQuery"},

  //{id:"32.", text:"AWS"},
  //{id:"33.", text:"GCP"},
  //{id:"34.", text:"Azure"},
  //{id:"35.", text:"DigitalOcean"},
  //{id:"36.", text:"Docker"},
  //{id:"37.", text:"Kubernetes"},

  //{id:"38.", text:"PostgreSQL"},
  //{id:"39.", text:"MySQL"},
  //{id:"40.", text:"MongoDB"},
  //{id:"41.", text:"Redis"},
  //{id:"42.", text:"Memcached"},
  //{id:"43.", text:"Oracle SQL"},
  //{id:"44.", text:"Microsoft SQL"},
  //{id:"45.", text:"Apache Cassandra"},
  //{id:"46.", text:"Couchbase"},
  //{id:"47.", text:"AWS RDS"},
  //{id:"48.", text:"Firebase"},
  //{id:"49.", text:"Elasticsearch"},
  //{id:"50.", text:"SQLite"},
];
